### ISSUE TITLE
the layer norm

### ISSUE THREAD

**Issue by InitialBug** [hengruo/QANet-pytorch#7]
nn.LayerNorm is a function with learnable parameters, it not only normalize the input, but also learn the possible data distribution, I think different layers in the encoder block(eg. conv layer,self-attention layer, feed forward layer) should have different learnable layernorm.

**Comment by hengruo** [comment]
@InitialBug You're right. I have tested the different layernorms but the results are almost identical, so I put this change off. Anyway, thanks a lot!
